spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active:
      - db
application:
  security:
    jwt:
      secret-key: eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5NzUzMjM0MCwiaWF0IjoxNjk3NTMyMzQwfQ.J9OyZ2OLIRdhXkAyd5CjA3aMND_8W1taiFKc2mwBPohMfYlY9k2ZK3BmK7jYojk-yds9-9r6HDDqfuYnapeY7A
      expiration: 86400000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days